name: Format

on:
  push:
    branches: [main]

jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/action-setup@v6
        with:
          version: 9.9.0

      - name: Setup Node.js environment
        uses: actions/setup-node@v7
        with:
          node-version-file: ".node-version"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Format
        run: pnpm run format

      - name: Add, Commit and Push
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "style: format code with prettier"
          commit_user_name: AlliotTech
          commit_user_email: 24980252+AlliotTech@users.noreply.github.com
          commit_author: "AlliotTech <24980252+AlliotTech@users.noreply.github.com>"
