name: release

on:
  push:
    tags:
      - "*"

jobs:
  changelog:
    name: Create release changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v6
        with:
          version: 9.9.0

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version-file: ".node-version"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Generate changelog
        run: pnpm exec changelogithub
        env:
          GITHUB_TOKEN: ${{secrets.MY_TOKEN}}

  release:
    needs: changelog
    strategy:
      matrix:
        platform: [ubuntu-latest]
    name: Release
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: main
          path: alist-web
          persist-credentials: false
          fetch-depth: 0
          submodules: recursive

      - name: Setup Node
        uses: actions/setup-node@v7
        with:
          node-version-file: "alist-web/.node-version"
          registry-url: "https://registry.npmjs.org"

      - uses: pnpm/action-setup@v6
        name: Install pnpm
        id: pnpm-install
        with:
          version: 9.9.0
          run_install: false

      - name: Checkout dist repo
        uses: actions/checkout@v7
        with:
          repository: AlliotTech/web-dist
          ref: main
          path: web-dist
          persist-credentials: false
          fetch-depth: 0

      - name: Build
        run: |
          mv alist-web/release.sh .
          bash release.sh
        env:
          CROWDIN_PROJECT_ID: ${{ secrets.CROWDIN_PROJECT_ID }}
          CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

      # - name: Publish npm
      #   run: |
      #     cd alist-web
      #     echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
      #     pnpm publish --no-git-checks
      #     cd ..
      #   env:
      #     NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Upload dist files
        uses: ad-m/github-push-action@881a6320fdb16eb5318c5054f31c218aec2b324c
        with:
          github_token: ${{ secrets.MY_TOKEN }}
          branch: main
          directory: web-dist
          repository: AlliotTech/web-dist

      - name: Release
        uses: softprops/action-gh-release@v3
        with:
          files: compress/*
